spring.application.name=Final_Project_Taha_Badri
spring.datasource.url=jdbc:postgresql://localhost:5432/final_project
spring.datasource.username=postgres
spring.datasource.password=taha
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8081
server.servlet.context-path=/api

recaptcha.secret=6Le51n4rAAAAAFBWF7VbbJcXeCLUyEqcz_Jbwu6g

spring.main.allow-bean-definition-overriding=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=Tahabadri83@gmail.com
spring.mail.password=aikfdbtotjzbrxxd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.security.oauth2.client.registration.keycloak.client-id=olol
spring.security.oauth2.client.registration.keycloak.client-secret=wgMA7FC3v74Z62LAwgkhdR1ANa8XhML1
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email,Role
#spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
#spring.security.oauth2.client.registration.keycloak.redirect-uri=http://localhost:8081/login/oauth2/code/keycloak
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8080/realms/test-1
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/test-1